[package]
name = "strategy_markowitz"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
tradingflow = { path = "../../tradingflow/crates/tradingflow", features = [
    "python",
] }
arrow = "59.1.0"
parquet = { version = "59.1.0", features = ["arrow", "zstd"] }
tokio = { version = "1.53.1", features = ["rt", "rt-multi-thread", "macros"] }
clap = { version = "4.6.5", features = ["derive"] }
chrono = "0.4.42"
indicatif = "0.18.6"
pyo3 = "0.29.0"
